# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import resources.resource as resource
from Draw import *
from XmlReader import *
from XmlWriter import *
import math

class Ui_MainWindow(QMainWindow):
    def __init__(self, MainWindow) -> None:
        super().__init__(MainWindow)
        self.viewPortPointsCoordinates = []
        self.viewPortLinesCoordinates = []
        self.viewPortPolygonsCoordinates = []
        self.displayFilePointsCoordinates = []
        self.displayFileLinesCoordinates = []
        self.displayFilePolygonsCoordinates = []
        self.window = Window(0, 0, 0, 0)
        self.viewport = Viewport(0, 0, 0, 0)
        self.windowRotation = 0
        self.windowTranslation = 0
        self.setupUi(MainWindow)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setObjectName("centralwidget")
        self.frameMain = QtWidgets.QFrame(self.centralwidget)
        self.frameMain.setGeometry(QtCore.QRect(10, 10, 1260, 676))
        self.frameMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMain.setObjectName("frameMain")
        self.widget_blue_2 = QtWidgets.QWidget(self.frameMain)
        self.widget_blue_2.setGeometry(QtCore.QRect(640, 10, 110, 60))
        self.widget_blue_2.setStyleSheet("background-color: blue")
        self.widget_blue_2.setObjectName("widget_blue_2")
        self.widget_yellow_2 = QtWidgets.QWidget(self.frameMain)
        self.widget_yellow_2.setGeometry(QtCore.QRect(760, 10, 110, 60))
        self.widget_yellow_2.setStyleSheet("background-color: yellow")
        self.widget_yellow_2.setObjectName("widget_yellow_2")
        self.widget_magenta_2 = QtWidgets.QWidget(self.frameMain)
        self.widget_magenta_2.setGeometry(QtCore.QRect(880, 10, 110, 60))
        self.widget_magenta_2.setStyleSheet("background-color: magenta")
        self.widget_magenta_2.setObjectName("widget_magenta_2")
        self.frameDrawer = QtWidgets.QFrame(self.frameMain)
        self.frameDrawer.setGeometry(QtCore.QRect(220, 80, 770, 586))
        self.frameDrawer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDrawer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDrawer.setObjectName("frameDrawer")
        self.widgetDrawer = Draw(self.frameDrawer)
        self.widgetDrawer.setGeometry(QtCore.QRect(10, 10, 750, 565))
        self.widgetDrawer.setStyleSheet("background-color: \'#3d3d3d\'")
        self.widgetDrawer.setObjectName("widgetDrawer")
        self.buttonSaveXml = QtWidgets.QPushButton(self.frameMain)
        self.buttonSaveXml.setGeometry(QtCore.QRect(220, 25, 70, 30))
        self.buttonSaveXml.setStyleSheet("")
        self.buttonSaveXml.setObjectName("buttonSaveXml")
        self.buttonSaveXml.clicked.connect(self.saveFileAsXml)
        self.buttonUseless = QtWidgets.QPushButton(self.frameMain)
        self.buttonUseless.setGeometry(QtCore.QRect(300, 25, 70, 30))
        self.buttonUseless.setObjectName("buttonUseless")
        self.buttonUseless.hide()
        self.labelCoordinates = QtWidgets.QLabel(self.frameMain)
        self.labelCoordinates.setGeometry(QtCore.QRect(380, 20, 171, 40))
        self.labelCoordinates.setObjectName("labelCoordinates")
        self.widgetDrawer.newPoint.connect(lambda p: self.labelCoordinates.setText(
            'Coordinates: ( %d : %d )' % (p.x(), p.y())))
        self.frame_2 = QtWidgets.QFrame(self.frameMain)
        self.frame_2.setGeometry(QtCore.QRect(1000, 10, 250, 280))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(10, 10, 231, 261))
        self.widget.setObjectName("widget")
        self.labelTranslation = QtWidgets.QLabel(self.widget)
        self.labelTranslation.setGeometry(QtCore.QRect(20, 30, 200, 16))
        self.labelTranslation.setObjectName("labelTranslation")
        self.labelRotation = QtWidgets.QLabel(self.widget)
        self.labelRotation.setGeometry(QtCore.QRect(20, 70, 200, 16))
        self.labelRotation.setObjectName("labelRotation")
        self.labelScale = QtWidgets.QLabel(self.widget)
        self.labelScale.setGeometry(QtCore.QRect(20, 110, 200, 16))
        self.labelScale.setObjectName("labelScale")
        self.labelWindowCoordinates = QtWidgets.QLabel(self.widget)
        self.labelWindowCoordinates.setGeometry(QtCore.QRect(20, 170, 200, 16))
        self.labelWindowCoordinates.setObjectName("labelWindowCoordinates")
        self.labelObjectsCoordinates = QtWidgets.QLabel(self.widget)
        self.labelObjectsCoordinates.setGeometry(
            QtCore.QRect(20, 210, 200, 16))
        self.labelObjectsCoordinates.setObjectName("labelObjectsCoordinates")
        self.treeWidget = QtWidgets.QTreeWidget(self.frameMain)
        self.treeWidget.setGeometry(QtCore.QRect(10, 10, 200, 656))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "ID")
        font = QtGui.QFont()
        font.setBold(True)
        self.treeWidget.headerItem().setFont(0, font)
        self.treeWidget.headerItem().setText(1, "Type")
        font = QtGui.QFont()
        font.setBold(True)
        self.treeWidget.headerItem().setFont(1, font)
        self.treeWidget.headerItem().setText(2, "Coordinates")
        font = QtGui.QFont()
        font.setBold(True)
        self.treeWidget.headerItem().setFont(2, font)
        self.treeWidget.setColumnWidth(0, 55)
        self.treeWidget.setColumnWidth(1, 60)
        # self.treeWidget.setColumnWidth(2, 40)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.frameTransformations = QtWidgets.QFrame(self.frameMain)
        self.frameTransformations.setGeometry(
            QtCore.QRect(1000, 300, 250, 366))
        self.frameTransformations.setAutoFillBackground(False)
        self.frameTransformations.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTransformations.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTransformations.setObjectName("frameTransformations")
        self.widgetTrasformations = QtWidgets.QWidget(
            self.frameTransformations)
        self.widgetTrasformations.setGeometry(QtCore.QRect(10, 10, 230, 480))
        self.widgetTrasformations.setStyleSheet("")
        self.widgetTrasformations.setObjectName("widgetTrasformations")
        self.buttonRotateLeft = QtWidgets.QPushButton(
            self.widgetTrasformations)
        self.buttonRotateLeft.setGeometry(QtCore.QRect(30, 80, 50, 30))
        self.buttonRotateLeft.setStyleSheet("")
        self.buttonRotateLeft.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/icons/rotate-left.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRotateLeft.setIcon(icon)
        self.buttonRotateLeft.setIconSize(QtCore.QSize(24, 24))
        self.buttonRotateLeft.setCheckable(False)
        self.buttonRotateLeft.setAutoExclusive(False)
        self.buttonRotateLeft.setObjectName("buttonRotateLeft")
        self.buttonRotateLeft.clicked.connect(self.buttonRotateLeftAction)
        self.buttonRotateRight = QtWidgets.QPushButton(
            self.widgetTrasformations)
        self.buttonRotateRight.setGeometry(QtCore.QRect(150, 80, 50, 30))
        self.buttonRotateRight.setStyleSheet("")
        self.buttonRotateRight.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/icons/rotate-right.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRotateRight.setIcon(icon1)
        self.buttonRotateRight.setIconSize(QtCore.QSize(24, 24))
        self.buttonRotateRight.setCheckable(False)
        self.buttonRotateRight.setAutoExclusive(False)
        self.buttonRotateRight.setObjectName("buttonRotateRight")
        self.buttonRotateRight.clicked.connect(self.buttonRotateRightAction)
        self.buttonUp = QtWidgets.QPushButton(self.widgetTrasformations)
        self.buttonUp.setGeometry(QtCore.QRect(90, 80, 50, 30))
        self.buttonUp.setStyleSheet("")
        self.buttonUp.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/icons/up-arrow.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonUp.setIcon(icon2)
        self.buttonUp.setIconSize(QtCore.QSize(24, 24))
        self.buttonUp.setCheckable(False)
        self.buttonUp.setAutoExclusive(False)
        self.buttonUp.setObjectName("buttonUp")
        self.buttonUp.clicked.connect(self.buttonUpAction)
        self.buttonDown = QtWidgets.QPushButton(self.widgetTrasformations)
        self.buttonDown.setGeometry(QtCore.QRect(90, 160, 50, 30))
        self.buttonDown.setStyleSheet("")
        self.buttonDown.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/icons/down-arrow.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonDown.setIcon(icon3)
        self.buttonDown.setIconSize(QtCore.QSize(24, 24))
        self.buttonDown.setCheckable(False)
        self.buttonDown.setAutoExclusive(False)
        self.buttonDown.setObjectName("buttonDown")
        self.buttonDown.clicked.connect(self.buttonDownAction)
        self.buttonLeft = QtWidgets.QPushButton(self.widgetTrasformations)
        self.buttonLeft.setGeometry(QtCore.QRect(30, 120, 50, 30))
        self.buttonLeft.setStyleSheet("")
        self.buttonLeft.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resources/icons/left-arrow.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonLeft.setIcon(icon4)
        self.buttonLeft.setIconSize(QtCore.QSize(24, 24))
        self.buttonLeft.setCheckable(False)
        self.buttonLeft.setAutoExclusive(False)
        self.buttonLeft.setObjectName("buttonLeft")
        self.buttonLeft.clicked.connect(self.buttonLeftAction)
        self.buttonRight = QtWidgets.QPushButton(self.widgetTrasformations)
        self.buttonRight.setGeometry(QtCore.QRect(150, 120, 50, 30))
        self.buttonRight.setStyleSheet("")
        self.buttonRight.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resources/icons/right-arrow.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRight.setIcon(icon5)
        self.buttonRight.setIconSize(QtCore.QSize(24, 24))
        self.buttonRight.setCheckable(False)
        self.buttonRight.setAutoExclusive(False)
        self.buttonRight.setObjectName("buttonRight")
        self.buttonRight.clicked.connect(self.buttonRightAction)
        self.spinBoxRotateStepSize = QtWidgets.QSpinBox(
            self.widgetTrasformations)
        self.spinBoxRotateStepSize.setValue(10)
        self.spinBoxRotateStepSize.setGeometry(QtCore.QRect(150, 260, 42, 25))
        self.spinBoxRotateStepSize.setObjectName("spinBoxRotateStepSize")
        self.labelMoveRotate = QtWidgets.QLabel(self.widgetTrasformations)
        self.labelMoveRotate.setGeometry(QtCore.QRect(60, 30, 111, 20))
        self.labelMoveRotate.setObjectName("labelMoveRotate")
        self.spinBoxTranslateStepSize = QtWidgets.QSpinBox(
            self.widgetTrasformations)
        self.spinBoxTranslateStepSize.setValue(10)
        self.spinBoxTranslateStepSize.setGeometry(
            QtCore.QRect(150, 220, 42, 25))
        self.spinBoxTranslateStepSize.setObjectName("spinBoxTranslateStepSize")
        self.labelTranslateStepSize = QtWidgets.QLabel(
            self.widgetTrasformations)
        self.labelTranslateStepSize.setGeometry(QtCore.QRect(30, 220, 100, 20))
        self.labelTranslateStepSize.setObjectName("labelTranslateStepSize")
        self.labelRotateStepSize = QtWidgets.QLabel(self.widgetTrasformations)
        self.labelRotateStepSize.setGeometry(QtCore.QRect(30, 260, 100, 20))
        self.labelRotateStepSize.setObjectName("labelRotateStepSize")
        self.buttonHome = QtWidgets.QPushButton(self.widgetTrasformations)
        self.buttonHome.setGeometry(QtCore.QRect(90, 120, 50, 30))
        self.buttonHome.setStyleSheet("")
        self.buttonHome.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resources/icons/home.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonHome.setIcon(icon6)
        self.buttonHome.setIconSize(QtCore.QSize(24, 24))
        self.buttonHome.setCheckable(False)
        self.buttonHome.setAutoExclusive(False)
        self.buttonHome.setObjectName("buttonHome")
        self.buttonHome.clicked.connect(self.buttonHomeAction)
        self.buttonZoomIn = QtWidgets.QPushButton(self.widgetTrasformations)
        self.buttonZoomIn.setGeometry(QtCore.QRect(150, 160, 50, 30))
        self.buttonZoomIn.setStyleSheet("")
        self.buttonZoomIn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("resources/icons/zoom-in.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonZoomIn.setIcon(icon7)
        self.buttonZoomIn.setIconSize(QtCore.QSize(24, 24))
        self.buttonZoomIn.setCheckable(False)
        self.buttonZoomIn.setAutoExclusive(False)
        self.buttonZoomIn.setObjectName("buttonZoomIn")
        self.buttonZoomOut = QtWidgets.QPushButton(self.widgetTrasformations)
        self.buttonZoomOut.setGeometry(QtCore.QRect(30, 160, 50, 30))
        self.buttonZoomOut.setStyleSheet("")
        self.buttonZoomOut.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("resources/icons/zoom-out.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonZoomOut.setIcon(icon8)
        self.buttonZoomOut.setIconSize(QtCore.QSize(24, 24))
        self.buttonZoomOut.setCheckable(False)
        self.buttonZoomOut.setAutoExclusive(False)
        self.buttonZoomOut.setObjectName("buttonZoomOut")
        self.radioButtonWindow = QtWidgets.QRadioButton(
            self.widgetTrasformations)
        self.radioButtonWindow.setGeometry(QtCore.QRect(130, 300, 89, 20))
        self.radioButtonWindow.setObjectName("radioButtonWindow")
        self.radioButtonObjects = QtWidgets.QRadioButton(
            self.widgetTrasformations)
        self.radioButtonObjects.setGeometry(QtCore.QRect(30, 300, 90, 20))
        self.radioButtonObjects.setObjectName("radioButtonObjects")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.actionOpen.triggered.connect(self.openFile)
        self.actionAbout.triggered.connect(self.triggerAbout)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Viewport Visualizer"))
        self.buttonSaveXml.setText(_translate("MainWindow", "Save XML"))
        self.buttonUseless.setText(_translate("MainWindow", "teste2"))
        self.labelCoordinates.setText(
            _translate("MainWindow", "coordinates:"))
        self.labelTranslation.setText(_translate("MainWindow", "Translation"))
        self.labelRotation.setText(_translate("MainWindow", "Rotation"))
        self.labelScale.setText(_translate("MainWindow", "Scale"))
        self.labelWindowCoordinates.setText(
            _translate("MainWindow", "Window Coordinates"))
        self.labelObjectsCoordinates.setText(
            _translate("MainWindow", "Object Coordinates"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        # self.treeWidget.setSortingEnabled(False)
        # self.treeWidget.topLevelItem(0).setText(
        #     0, _translate("MainWindow", "Point"))
        # self.treeWidget.topLevelItem(0).setText(
        #     1, _translate("MainWindow", "p1"))
        # self.treeWidget.topLevelItem(1).setText(
        #     0, _translate("MainWindow", "Line"))
        # self.treeWidget.topLevelItem(1).setText(
        #     1, _translate("MainWindow", "l1"))
        # self.treeWidget.topLevelItem(2).setText(
        #     0, _translate("MainWindow", "Polygon"))
        # self.treeWidget.topLevelItem(2).setText(
        #     1, _translate("MainWindow", "p1"))
        # self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.labelMoveRotate.setText(
            _translate("MainWindow", "Move/Rotate/Scale"))
        self.labelTranslateStepSize.setText(
            _translate("MainWindow", "Traslation step size"))
        self.labelRotateStepSize.setText(
            _translate("MainWindow", "Rotation step size"))
        self.radioButtonWindow.setText(_translate("MainWindow", "Window"))
        self.radioButtonObjects.setText(_translate("MainWindow", "Objects"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

    def calcular(self, x, y, matrix):
        # print(x,y)
        print(matrix @ np.array([x, y, 1]))
        coord = matrix @ np.array([x, y, 1])
        return (coord[0], coord[1])

    def newWinCoordinates(self):
        return 0
        coord = self.window.getCoordinates()
        print('coord :', coord)
        # a = self.calcular(coord[0][0], 0, self.window.getTransformationMatrix())
        # b = self.calcular(coord[0][0], coord[1][0], self.window.getTransformationMatrix())
        # c = self.calcular(coord[1][0], 0, self.window.getTransformationMatrix())
        # d = self.calcular(coord[1][0], coord[1][1], self.window.getTransformationMatrix())
       # print(a,b,c,d)
        xwMin, ywMin = self.calcular(
            *coord[0], self.window.getTransformationMatrix())
        xwmax, ywmax = self.calcular(
            *coord[1], self.window.getTransformationMatrix())
        # print(xwMin,ywMin, xwmax,ywmax)

        newWindow = Window(xwMin, xwmax, ywMin, ywmax)

        print('wincoord', newWindow.getCoordinates())
        # conversor = WindowToViewportConversor()
        # # self.window = xmlReader.getWindow()
        # # self.viewport = xmlReader.getViewport()
        # # self.displayFilePointsCoordinates = xmlReader.getPontos()
        # # self.displayFileLinesCoordinates = xmlReader.getRetas()
        # # self.displayFilePolygonsCoordinates = xmlReader.getPoligonos()
        # print(self.viewport)
        # viewportWidth = int(self.viewport.getXvMax() - self.viewport.getXvMin())
        # viewportHeight = int(self.viewport.getYvMax() - self.viewport.getYvMin())
        # self.widgetDrawer.setGeometry(QtCore.QRect(10, 10, viewportWidth, viewportHeight))

        # for point in self.displayFilePointsCoordinates:
        #     convertedPoint = conversor.convertToViewport(
        #         point, newWindow, self.viewport)
        #     self.viewPortPointsCoordinates.append(convertedPoint)

        # for line in self.displayFileLinesCoordinates:
        #     convertedLine = conversor.convertToViewport(
        #         line, newWindow, self.viewport)
        #     self.viewPortLinesCoordinates.append(convertedLine)

        # for polygon in self.displayFilePolygonsCoordinates:
        #     convertedPolygon = conversor.convertToViewport(
        #         polygon, newWindow, self.viewport)
        #     self.viewPortPolygonsCoordinates.append(convertedPolygon)

        # for ponto in self.viewPortPointsCoordinates:
        #     self.widgetDrawer.drawPoint(ponto)

        # for line in self.viewPortLinesCoordinates:
        #     self.widgetDrawer.drawLine(line)

        # for polygon in self.viewPortPolygonsCoordinates:
        #     self.widgetDrawer.drawPolygon(polygon)

        # print('new win coordinates', coord)

    def buttonUpAction(self):
        print('moveu up')
        self.window.addTranslation(0, self.spinBoxTranslateStepSize.value())
        a = self.window.getTranslation()
        x = str(a[0])
        y = str(a[1])
        self.labelTranslation.setText(
            'Translation     (' + '<b>X:  </b> ' + x + ', ' + '<b>Y:  </b> ' + y+')')
        self.newWinCoordinates()

    def buttonDownAction(self):
        print('moveu down')
        self.window.addTranslation(0, -self.spinBoxTranslateStepSize.value())
        a = self.window.getTranslation()
        x = str(a[0])
        y = str(a[1])
        self.labelTranslation.setText(
            'Translation     (' + '<b>X:  </b> ' + x + ', ' + '<b>Y:  </b> ' + y+')')
        self.newWinCoordinates()

    def buttonLeftAction(self):
        print('moveu left')
        self.window.addTranslation(-self.spinBoxTranslateStepSize.value(), 0)
        a = self.window.getTranslation()
        x = str(a[0])
        y = str(a[1])
        self.labelTranslation.setText(
            'Translation     (' + '<b>X:  </b> ' + x + ', ' + '<b>Y:  </b> ' + y+')')
        self.newWinCoordinates()

    def buttonRightAction(self):
        print('moveu right')
        self.window.addTranslation(self.spinBoxTranslateStepSize.value(), 0)
        a = self.window.getTranslation()
        x = str(a[0])
        y = str(a[1])
        self.labelTranslation.setText(
            'Translation     (' + '<b>X:  </b> ' + x + ', ' + '<b>Y:  </b> ' + y+')')
        self.newWinCoordinates()

    def buttonHomeAction(self):
        print('moveu home')
        self.window.resetTransformation()
        self.newWinCoordinates()
        self.widgetDrawer.erase()
        a = self.window.getTranslation()
        x = str(a[0])
        y = str(a[1])
        self.labelTranslation.setText(
            'Translation     (' + '<b>X:  </b> ' + x + ', ' + '<b>Y:  </b> ' + y+')')

    def buttonRotateLeftAction(self):
        print('rotate left')
        self.window.addRotation(-self.spinBoxRotateStepSize.value())
        print(self.window.getRotation())
        print(math.radians(self.window.getRotation()))
        b = self.window.getRotation()
        theta = str(b)
        self.labelRotation.setText(
            'Rotation     (' + '<b>Theta:  </b> ' + theta + 'º)')
        self.newWinCoordinates()

    def buttonRotateRightAction(self):
        print('rotate right')
        self.window.addRotation(self.spinBoxRotateStepSize.value())
        print(self.window.getRotation())
        print(math.radians(self.window.getRotation()))
        b = self.window.getRotation()
        theta = str(b)
        self.labelRotation.setText(
            'Rotation     (' + '<b>Theta:  </b> ' + theta + 'º)')
        self.newWinCoordinates()

    def triggerAbout(self):
        my_dialog = QDialog(MainWindow)
        my_dialog.setWindowTitle("About")
        # my_dialog.setWindowModality(Qt.ApplicationModal)
        my_dialog.setGeometry(0, 0, 400, 300)
        my_dialog.move(MainWindow.rect().center())
        # my_dialog.move(QDesktopWidget().availableGeometry().center().x() - self.frameGeometry().center().x() * 0.5, QDesktopWidget().availableGeometry().center().y() - self.frameGeometry().center().y() * 0.5)
        self.labelNameAbout = QtWidgets.QLabel(my_dialog)

        # self.labelNameAbout.setGeometry(QtCore.QRect(10, 270, 101, 20))
        self.labelNameAbout.setObjectName("labelNameAbout")
        self.labelNameAbout.move(my_dialog.rect().center())
        self.labelNameAbout.setText(
            u"<html><head/><body><p><a href=\"https://github.com/Jefesonk1\"><span style=\" text-decoration: underline; color:#0000ff;\">Github</span></a></p></body></html>")
        self.labelNameAbout.setOpenExternalLinks(True)
        # self.labelNameAbout.setText("Feito por: Jefeson Martins Delazeri\n email: jefesonk1@outlook.com \n github: https://github.com/Jefesonk1")
        my_dialog.exec_()  #
        # self.about = QtWidgets.QDialog()

        # self.aboutUi = Ui_Dialog()
        # self.aboutUi.setupUi(self.about)
        # self.about.show()

    def openFileNameDialog(self):
        options = QFileDialog.Options()
        fileName, _ = QFileDialog.getOpenFileName(
            self.centralwidget, "Open", "", "XLM Files (*.xml)", options=options)
        if fileName:
            return fileName

    def saveFileDialog(self):
        options = QFileDialog.Options()
        fileDialog = QFileDialog(self, 'Projects')
        fileDialog.setAttribute(Qt.WA_QuitOnClose, False)
        fileName, _ = fileDialog.getSaveFileName(
            self.centralwidget, "Save", "", "XML Files (*.xml)", options=options)
        if fileName:
            return fileName

    def saveFileAsXml(self):
        pathFilename = self.saveFileDialog()
        if (pathFilename):
            xml = XmlWriter(pathFilename)
            xml.write(self.viewPortPointsCoordinates,
                      self.viewPortLinesCoordinates, self.viewPortPolygonsCoordinates)
            self.buttonSaveXml.hide()
            self.buttonSaveXml.setText("Saved")

    def fillObjectsList(self, objectList: Union[Point, Line, Polygon]):
        if isinstance(objectList, list):
            if isinstance(objectList[0], Polygon):
                print('Polygon')
                items = []
                for index, polygon in enumerate(objectList):
                    item = None
                    objectId = 'pl'+str(index)
                    item = QTreeWidgetItem([objectId, 'Polygon'])
                    # print(polygon, index)
                    for indexPoint, point in enumerate(polygon.getPolygon()):
                        xCoord = str(point.getPoint()[0])
                        yCoord = str(point.getPoint()[1])
                        coord = '('+xCoord+', '+yCoord+')'
                        pointId = 'p'+str(indexPoint)
                        child = QTreeWidgetItem([pointId, 'Point', coord])
                        item.addChild(child)
                    items.append(item)
                self.treeWidget.insertTopLevelItems(0, items)
            elif isinstance(objectList[0], Line):
                print('Line')
                items = []
                for index, key in enumerate(objectList):
                    p1, p2 = key.getLine()
                    xCoordp1 = str(p1.getPoint()[0])
                    yCoordp1 = str(p1.getPoint()[1])
                    xCoordp2 = str(p2.getPoint()[0])
                    yCoordp2 = str(p2.getPoint()[1])
                    coord = '('+xCoordp1+', '+yCoordp1+')'
                    coord2 = '('+xCoordp2+', '+yCoordp2+')'
                    objectId = 'l'+str(index)
                    item = QTreeWidgetItem([objectId, 'Line'])
                    child = QTreeWidgetItem(['p1', 'Point', coord])
                    child2 = QTreeWidgetItem(['p2', 'Point', coord2])
                    item.addChild(child)
                    item.addChild(child2)
                    items.append(item)
                self.treeWidget.insertTopLevelItems(0, items)

            elif isinstance(objectList[0], Point):
                print('Point')
                items = []
                for index, key in enumerate(objectList):
                    xCoord = str(key.getPoint()[0])
                    yCoord = str(key.getPoint()[1])
                    coord = '('+xCoord+', '+yCoord+')'
                    objectId = 'p'+str(index)
                    item = QTreeWidgetItem([objectId, 'Point', coord])
                    items.append(item)
                self.treeWidget.insertTopLevelItems(0, items)

    def initLabels(self):
       # fazer funcao update labels
        a = self.window.getTranslation()
        x = str(a[0])
        y = str(a[1])
        self.labelTranslation.setText(
            'Translation     (' + '<b>X axis:  </b> ' + x + ', ' + '<b>Y axis:  </b> ' + y+')')

        b = self.window.getRotation()
        theta = str(b)
        self.labelRotation.setText(
            'Rotation     (' + '<b>Theta:  </b> ' + theta + 'º)')

        c = self.window.getScale()
        x = str(c[0])
        y = str(c[1])
        self.labelScale.setText(
            'Scale     (' + '<b>X axis:  </b> ' + x + ', ' + '<b>Y axis:  </b> ' + y + ')')

        d = self.window.getCoordinates()
        xMin = str(d[0][0])
        yMin = str(d[0][1])
        xMax = str(d[1][0])
        yMax = str(d[1][1])
        self.labelWindowCoordinates.setText(
            '<b>wMin:</b> (' + xMin + ', ' + yMin + ') <b>wMax:</b> (' + xMax + ', ' + yMax + ')')

    def openFile(self):
        filePath = self.openFileNameDialog()
        xmlReader = XmlReader(filePath)
        conversor = WindowToViewportConversor()
        self.window = xmlReader.getWindow()
        self.viewport = xmlReader.getViewport()
        self.displayFilePointsCoordinates = xmlReader.getPontos()
        self.displayFileLinesCoordinates = xmlReader.getRetas()
        self.displayFilePolygonsCoordinates = xmlReader.getPoligonos()
        print(self.viewport)

        self.fillObjectsList(self.displayFileLinesCoordinates)
        self.fillObjectsList(self.displayFilePointsCoordinates)
        self.fillObjectsList(self.displayFilePolygonsCoordinates)

        self.initLabels()
        viewportWidth = int(self.viewport.getXvMax() -
                            self.viewport.getXvMin())
        viewportHeight = int(self.viewport.getYvMax() -
                             self.viewport.getYvMin())
        self.widgetDrawer.setGeometry(QtCore.QRect(
            10, 10, viewportWidth, viewportHeight))

        for point in self.displayFilePointsCoordinates:
            convertedPoint = conversor.convertToViewport(
                point, self.window, self.viewport)
            self.viewPortPointsCoordinates.append(convertedPoint)

        for line in self.displayFileLinesCoordinates:
            convertedLine = conversor.convertToViewport(
                line, self.window, self.viewport)
            self.viewPortLinesCoordinates.append(convertedLine)

        for polygon in self.displayFilePolygonsCoordinates:
            convertedPolygon = conversor.convertToViewport(
                polygon, self.window, self.viewport)
            self.viewPortPolygonsCoordinates.append(convertedPolygon)

        for ponto in self.viewPortPointsCoordinates:
            self.widgetDrawer.drawPoint(ponto)

        for line in self.viewPortLinesCoordinates:
            self.widgetDrawer.drawLine(line)

        for polygon in self.viewPortPolygonsCoordinates:
            self.widgetDrawer.drawPolygon(polygon)


print(resource)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    _Font = QFont("Tahoma", 10)
    QApplication.setFont(_Font)
    MainWindow = QtWidgets.QMainWindow()
    styleFile = QFile("style.qss")
    styleFile.open(QFile.ReadOnly)
    stylesheet = QTextStream(styleFile).readAll()
    app.setStyleSheet(stylesheet)

    ui = Ui_MainWindow(MainWindow)
    # ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
